---
# Copyright 2018-present Open Networking Foundation
# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: Service
metadata:
  name: oai-enb-new
spec:
  selector:
    app: oai-enb-new
  clusterIp: None
  ports:
    - name: s1ap
      port: 36412
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oai-enb-new
  labels:
    app: oai-enb-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-enb-new
  serviceName: oai-enb-new
  template:
    metadata:
      labels:
        app: oai-enb-new
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
                { "name": "s1u-net", "interface": "s1u-net" }
        ]'
    spec:
      # Required if working with Linux bound devices so that kernel does not
      # reply to GTP-U packets
      #initContainers:
      #- name: init
      #  image: "ngick8stesting/c3po-init"
      #  command: [ "sh", "-xec"]
      #  securityContext:
      #    capabilities:
      #      add:
      #        - NET_ADMIN
      #  args:
      #  - iptables -I OUTPUT -p icmp --icmp-type destination-unreachable -j DROP;
      containers:
      - name: oai-enb-new
        image: {{ .Values.global.image }}
        imagePullPolicy: {{ .Values.global.imagepullpolicy }}
        stdin: true
        tty: true
        command: ["bash", "-xc"]
        args:
        - while true; do sleep 3600; done
        resources:
          limits:
            intel.com/sriov: 1
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - NET_ADMIN
